name: ccsd

services:
  backend:
    build: ./ccsd
    restart: always
    ports:
      - 8082:8082
    volumes:
      - ./ccsd/src:/app/src
    environment:
      MONGO_URI: ${mongo_uri}
    networks:
      - mognonetwork

  dashboard-js:
    build: ./dashboard
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./dashboard/src:/app/src
    networks:
      - mognonetwork
    depends_on:
      - backend

  front-ui:
    build: ./frontui
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontui:/usr/local/apache2/htdocs/
    networks:
      - mognonetwork
    depends_on:
      - backend

  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./db:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME:
  #     MONGO_INITDB_ROOT_PASSWORD:
  #   networks:
  #     - mognonetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_SERVER: ypfullstack.srddo7z.mongodb.net
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASSWORD}
      ME_CONFIG_MONGODB_URL: ${mongo_uri}
      # ME_CONFIG_SITE_BASEURL: /
      ME_CONFIG_BASICAUTH: false
    networks:
      - mognonetwork

networks:
  mognonetwork:
    driver: bridge

volumes:
  db_data:
